const image1 = require("../assets/images/global-footprint-banner.jpg");
const image2 = require("../assets/images/Ingredients-Circle.png");
const image3 = require("../assets/images/Fi_Logo_RGB_Europe_2023.png");
const img1 = require("../assets/images/banner-nuts-new.jpg");
const img2 = require("../assets/images/banner-spices-landing-page-new.jpg");
const img3 = require("../assets/images/dairy-main-new.jpg");
const img4 = require("../assets/images/coffee-min.jpg");
const img5 = require("../assets/images/cocoa-expertise-min-new.png");
const mid1 = require("../assets/images/health-and-wellness-home.jpg");
const mid2 = require("../assets/images/indulgence-sensory.jpg");
const mid3 = require("../assets/images/plant-based-alternatives.jpg");
const mid4 = require("../assets/images/spices-ofi-pr.jpg");
const mid5 = require("../assets/images/natural-and-clean.png");
export { image1, image2, image3, img1, img2, img3, img4, img5, mid1, mid2, mid3, mid4, mid5 };
